[workspace]
members = ["src/axum_server", "src/common", "src/grpc_server"]
resolver = "2"

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
prost = "0.13"
tonic = "0.12"
tonic-build = "0.12"
tokio = "1"
tokio-stream = "0.1"
